### ISSUE TITLE
How to use it in pytest based testing?

### ISSUE THREAD

**Issue by youkaichao** [ezyang/expecttest#18]
The readme seems to be written for testcase only.

**Comment by ezyang** [comment]
Works for pytest with no modifications, I use it with pytest all the time.

**Comment by youkaichao** [comment]
Any examples? In the readme, it needs to be used with `expecttest.TestCase.assertExpectedInline` . In pytest, I simply use `assert a == b` .

**Comment by ezyang** [comment]
oh I see. Use `assert_expected_inline` in this case. One downside is you do not get pytest assert rewriting but we try to give a good error message anyway.

**Comment by youkaichao** [comment]
That's great, thanks!
